version: "3"

services:
  api:
    depends_on:
      - db
    image: imotechsl/kenecare-api:${ENV}
    container_name: kenecare-api-${ENV}
    ports:
      - 8500:8000
    networks:
      - kenecare-staging-net
      - mysql-db-net
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_CONNECTION_LIMIT=$DB_CONNECTION_LIMIT
      - NODE_ENV=$NODE_ENV
      - APP_PORT=$APP_PORT
      - SESSION_SECRET=$SESSION_SECRET
      - API_BASE_URL=$API_BASE_URL
      - FRONTEND_URL=$FRONTEND_URL
      - PATIENTS_JWT_SECRET=$PATIENTS_JWT_SECRET
      - ADMINS_JWT_SECRET=$ADMINS_JWT_SECRET
      - JWT_AUDIENCE=$JWT_AUDIENCE
      - JWT_ADMIN_AUDIENCE=$JWT_ADMIN_AUDIENCE
      - JWT_ISSUER=$JWT_ISSUER
      - OM_WEB_PAYMENT_URL=$OM_WEB_PAYMENT_URL
      - OM_MERCHANT_KEY=$OM_MERCHANT_KEY
      - OM_BASIC_AUTH_TOKEN=$OM_BASIC_AUTH_TOKEN
      - OM_RETURN_URL=$OM_RETURN_URL
      - OM_CANCEL_URL=$OM_CANCEL_URL
      - OM_NOTIFICATION_URL=$OM_NOTIFICATION_URL
      - OM_TOKEN_URL=$OM_TOKEN_URL
      - OM_TRANSACTION_STATUS_URL=$OM_TRANSACTION_STATUS_URL
      - OM_CURRENCY=$OM_CURRENCY
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - SENDGRID_EMAIL=$SENDGRID_EMAIL
    volumes:
      - kenecare-app-data-staging:/usr/src/app/src/public/upload

  db:
    image: mysql:8.0.2
    container_name: mysql-db
    restart: unless-stopped
    # command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
    ports:
      - 3307:3306
    volumes:
      - ./src/db/kenecare.sql:/docker-entrypoint-initdb.d/init.sql
      - kenecare-db-data-staging:/var/lib/mysql
    networks:
      - mysql-db-net

volumes:
  kenecare-db-data-staging:
    name: kenecare-db-data-staging
  kenecare-app-data-staging:
    name: kenecare-app-data-staging

networks:
  kenecare-staging-net:
    name: kenecare-staging-net
    driver: bridge
  mysql-db-net:
    name: mysql-db-net
    driver: bridge
