version: '3'

services:
  api:
    depends_on:
      - db
    image: imotechsl/kenecare-api:${ENV}
    container_name: kenecare-api-${ENV}
    ports:
      - 8001:8000
    networks:
      - kenecare-staging-net
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_CONNECTION_LIMIT=$DB_CONNECTION_LIMIT
      - NODE_ENV=$NODE_ENV
      - APP_PORT=$APP_PORT   
    volumes:
      - kenecare-app-data:/usr/src/app/src/public/upload
    

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    # command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - 3306:3306
    volumes:
      - ./src/db/kenecare.sql:/docker-entrypoint-initdb.d/init.sql
      - kenecare-db-data:/var/lib/mysql
    networks:
      - mysql-db-net
      - kenecare-staging-net


volumes:
  kenecare-db-data:
    name: kenecare-db-data
  kenecare-app-data:
    name: kenecare-app-data

networks:
  kenecare-staging-net:
    name: kenecare-staging-net
    driver: bridge
  mysql-db-net:
    name: mysql-db-net
    driver: bridge