services:
  api:
    image: ${IMAGE_NAME}:${TAG:-prod}
    container_name: kenecare-api-${ENV:-prod}
    ports:
      - 9500:8000
    networks:
      - kenecare-prod-net
    restart: always
    env_file: ./.env.${ENV:-prod}
    volumes:
      - kenecare-app-data-staging:/usr/src/app/src/public/upload
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/api/v1/health-check"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 1s

volumes:
  # kenecare-app-data-prod:
  #   name: kenecare-app-data-prod
  kenecare-app-data-staging:
    name: kenecare-app-data-staging

networks:
  kenecare-prod-net:
    name: kenecare-prod-net
    driver: bridge
