version: "3"

services:
  admin:
    depends_on:
      - db
    build:
      context: .
    container_name: kenecare-api-${ENV}
    image: imotechsl/kenecare-api:${ENV}
    ports:
      - 8500:8000
    networks:
      - kenecare-net
    restart: always
    env_file: ./.env.${ENV}
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_CONNECTION_LIMIT=$DB_CONNECTION_LIMIT
      - NODE_ENV=$NODE_ENV
      - APP_PORT=$APP_PORT
      - SESSION_SECRET=$SESSION_SECRET
      - API_BASE_URL=$API_BASE_URL
      - FRONTEND_URL=$FRONTEND_URL
      - PATIENTS_JWT_SECRET=$PATIENTS_JWT_SECRET
      - ADMINS_JWT_SECRET=$ADMINS_JWT_SECRET
      - JWT_AUDIENCE=$JWT_AUDIENCE
      - JWT_ADMIN_AUDIENCE=$JWT_ADMIN_AUDIENCE
      - JWT_ISSUER=$JWT_ISSUER
      - OM_WEB_PAYMENT_URL=$OM_WEB_PAYMENT_URL
      - OM_MERCHANT_KEY=$OM_MERCHANT_KEY
      - OM_BASIC_AUTH_TOKEN=$OM_BASIC_AUTH_TOKEN
      - OM_RETURN_URL=$OM_RETURN_URL
      - OM_CANCEL_URL=$OM_CANCEL_URL
      - OM_NOTIFICATION_URL=$OM_NOTIFICATION_URL
      - OM_TOKEN_URL=$OM_TOKEN_URL
      - OM_TRANSACTION_STATUS_URL=$OM_TRANSACTION_STATUS_URL
      - OM_CURRENCY=$OM_CURRENCY
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - SENDGRID_EMAIL=$SENDGRID_EMAIL
    volumes:
      - .:/usr/src/app

  db:
    image: mysql:latest
    container_name: mysql-db-${ENV}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env.${ENV}
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_HOST=MYSQL_ROOT_HOST
    ports:
      - 3307:3306
    volumes:
      - ./src/db/kenecare.sql:/docker-entrypoint-initdb.d/init.sql
      - kenecare-api-db-data:/var/lib/mysql
    networks:
      - kenecare-net
  # nginx:
  #   build:
  #     context: ./nginx
  #   image: imotechsl/kenecare-nginx:${ENV}
  #   container_name: kenecare-nginx-${ENV}
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - admin
  #   networks:
  #     - kenecare-net

volumes:
  kenecare-api-db-data:
    name: kenecare-api-db-data

networks:
  kenecare-net:
    name: kenecare-net
    driver: bridge
