services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    env_file: ./redis.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  redis-data:
    name: redis-data

networks:
  redis-net:
    name: redis-net
    driver: bridge
    attachable: true
