const { env } = process;

module.exports = {
  appPort: env.APP_PORT,
  appHost: env.HOST,
  appBaseURL: env.BASE_URL,
  apiBaseURL: env.API_BASE_URL,
  adminJwtSecret: env.ADMINS_JWT_SECRET,
  awsBucketName: env.AWS_BUCKET_NAME,
  awsAccessSecretKey: env.AWS_ACCESS_SECRET_KEY,
  awsAccessKeyId: env.AWS_ACCESS_KEY_ID,
  awsRegion: env.AWS_REGION,
  clientAppUrl: env.CLIENT_APP_URL,
  timeSlotInterval: env.TIME_SLOT_INTERVAL,
  nodeEnv: env.NODE_ENV,
  dbHost: env.DB_HOST,
  dbUsername: env.DB_USER,
  dbPassword: env.DB_PASS,
  dbName: env.DB_NAME,
  dbPort: env.DB_PORT,
  dbConnectionLimit: env.DB_CONNECTION_LIMIT,
  encryptionKey: env.ENCRYPTION_KEY,
  sessionSecret: env.SESSION_SECRET,
  patientJwtSecret: env.PATIENTS_JWT_SECRET,
  jwtIssuer: env.JWT_ISSUER,
  jwtAudience: env.JWT_AUDIENCE,
  jwtAdminAudience: env.JWT_ADMIN_AUDIENCE,
  monimeeApiKey: env.MONIMEE_API_KEY,
  monimeeSpaceId: env.MONIMEE_SPACE_ID,
  monimeeApiUrl: env.MONIMEE_API_URL,
  twilioAccountSID: env.TWILIO_ACCOUNT_SID,
  twilioAuthToken: env.TWILIO_AUTH_TOKEN,
  twilioPhoneNumber: env.TWILIO_PHONE_NUMBER,
  paymentCancelUrl: env.PAYMENT_CANCEL_URL,
  paymentReturnUrl: env.PAYMENT_RETURN_URL,
  redisHost: env.REDIS_HOST,
  redisPort: env.REDIS_PORT,
  redisUsername: env.REDIS_USERNAME,
  redisPassword: env.REDIS_PASSWORD,
  sendGridApiKey: env.SENDGRID_API_KEY,
  sendGridSenderEmail: env.SENDGRID_EMAIL,
  smsHiveClientId: env.SMS_HIVE_CLIENT_ID,
  smsHiveClientSecret: env.SMS_HIVE_CLIENT_SECRET,
  smsHiveAuthToken: env.SMS_HIVE_AUTH_TOKEN,
  smsHiveUrl: env.SMS_HIVE_URL,
  streamSdkApiKey: env.STREAM_SDK_API_KEY,
  streamSdkApiSecret: env.STREAM_SDK_API_SECRET,
  zoomAccountId: env.ZOOM_ACCOUNT_ID,
  zoomClientId: env.ZOOM_CLIENT_ID,
  zoomClientSecret: env.ZOOM_CLIENT_SECRET,
  zoomSecretToken: env.ZOOM_SECRET_TOKEN,
  zoomVerificationToken: env.ZOOM_VERIFICATION_TOKEN,
  zoomAccessTokenUrl: env.ZOOM_ACCESS_TOKEN_URL,
  zoomApiUrl: env.ZOOM_API_URL,
  zoomWebSocketSubscriptionId: env.ZOOM_WEB_SOCKET_SUBSCRIPTION_ID,
  kenecareAdminEmail: env.KENECARE_ADMIN_EMAIL,
  kenecareSupportEmail: env.KENECARE_SUPPORT_EMAIL,
  kenecareMeetingEmail: env.KENECARE_MEETING_EMAIL,
  kenecareInfoEmail: env.KENECARE_INFO_EMAIL,
  kenecareAppointmentsEmail: env.KENECARE_APPOINTMENTS_EMAIL,
  maxAuthRequest: parseInt(env.MAX_AUTH_REQUEST, 10),
  maxOtpRequest: parseInt(env.MAX_OTP_REQUEST, 10),
  maxRequest: parseInt(env.MAX_REQUEST, 10),
  maxFileUploadRequest: parseInt(env.MAX_FILE_UPLOAD_REQUEST, 10),
  maxAdminRequest: parseInt(env.MAX_ADMIN_REQUEST, 10),
};
