build-nginx-dev:
	docker build \
	-t imotechsl/kenecare-nginx:development \
	--build-arg NGINXFILE=./default.conf  \
	.
	
build-nginx-prod:
	docker build \
	-t imotechsl/kenecare-nginx:production \
	--build-arg NGINXFILE=./default.conf \
	.