openapi: '3.0.3'
info:
  title: "Kenecare API"
  description: "Kenecare Api"

  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "developer@imo-tech.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "1.0.0"

servers:
  - url: "https://test.api.kenecare.com"
  - url: "http://localhost:8000/api/v1"
tags:
  - name: "Auth"
    description: "Everything about Authentication"
  - name: "Admin"
    description: "All admin related routes"
  - name: "Doctors"
    description: "All doctor related routes"

paths:
  /auth/login:
    post:
      tags:
        - "Auth"
      summary: "Route for loggin user in"
      requestBody:
        description: "login user"
        content:
          application/json:
            schema:
              type: object
              properties:
                mobileNumber:
                  type: string
                  example: +23278121212
                password:
                  type: string
                  example: strongpassword
      responses:
        '200':
          description: Successful login
          content:
           application/json:
             schema: 
               type: object
               properties:
                 token:
                   type: string

 