name: production-workflow

on:
  workflow_dispatch:
  push:
    branches: ["production"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: imotechsl/kenecare-api-prod
  IMAGE_TAG: 1.0.${{github.run_number}}
  GH_RUN_NUMBER: ${{github.run_number}}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build-and-push-image:
    runs-on: ["self-hosted", "imotechsl-apps"]

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: "v2.2.4"

      - name: Check if Cosign is installed
        if: github.event_name != 'pull_request'
        run: cosign version

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.1.0

      - name: Login to Registry ${{env.REGISTRY}}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{env.REGISTRY}}
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}

      - name: Extract Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          tags: type=sha, format=long

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: Dockerfile.prod
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          labels: ${{steps.docker-metadata.outputs.labels}}

      - name: Sign Docker Image
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{steps.docker-metadata.outputs.tags}}
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
          DIGEST: ${{steps.build-and-push.outputs.digest}}

      - name: Copy Variables
        run: cp ~/.env.kenecare.api-prod ./.env
